services:
  - type: web
    name: protein-viewer
    env: node
    buildCommand: npm install && npm run build
    startCommand: serve -s build
    staticPublishPath: ./build
    buildPaths:
      - public/filtered_pdbs/
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
